# Generated by Django 3.1 on 2020-08-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_owner'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('scheduled_date', models.DateField(blank=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_transfers_in', to='account.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_transfers_out', to='account.account')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_by', to='transfer.transfer')),
            ],
        ),
    ]
